neve:
  web:
    Log:
      RequestHeader: true
      RequestBody: true
      ResponseHeader: true
      ResponseBody: true
      Level: "warn"

    Server:
      ContextPath: ""
      Port: 8080
      ReadTimeout: 15
      WriteTimeout: 15
      IdleTimeout: 15

version: "v1.0.0"
swagger:
  enable: true
  path: "/swagger-ui"
