neve:
  web:
    Log:
      RequestHeader: true
      RequestBody: true
      ResponseHeader: true
      ResponseBody: true
      Level: "info"

    Server:
      ContextPath: ""
      Port: 8080
      ReadTimeout: 15
      WriteTimeout: 15
      IdleTimeout: 15

  DataSources:
    testDB:
      DriverName: "mysql"
      DriverInfo: "test:123@tcp(127.0.0.1:3306)/test?timeout=10s&readTimeout=15s&charset=uft8"
      MaxCoon: 1000
      MaxIdleConn: 500
      ConnMaxLifetime: 0

gobatis:
  mapper:
    dir: "mapper"
  log:
    level: INFO
  pagehelper:
    enable: true

version: "v1.0.0"
swagger:
  enable: true
  path: "/swagger-ui"
