info:
  contact:
    email: lxf1222@163.com
    name: Xiongfa.Li
  description: Neve Example
  title: Neve Example
  version: v1.0.0
paths:
  /keys/{key}:
    delete:
      description: Delete Key and Value
      parameters:
      - description: key
        in: path
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            items:
              type: string
            type: array
        "404":
          description: Not Found
          schema:
            items:
              type: string
            type: array
      summary: Delete Key and Value
      tags:
      - cache
    get:
      description: Get Value
      parameters:
      - description: key
        in: path
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            items:
              type: string
            type: array
        "404":
          description: Not Found
          schema:
            items:
              type: string
            type: array
      summary: Get Value
      tags:
      - cache
    put:
      description: Add Key and Value
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            items:
              type: string
            type: array
      summary: Add Key and Value
      tags:
      - cache
swagger: "2.0"
