info:
  contact:
    email: lxf1222@163.com
    name: Xiongfa.Li
  description: Neve Example
  title: Neve Example
  version: v1.0.0
paths:
  /keys/{key}:
    delete:
      description: Delete Key and Value
      parameters:
      - description: key
        in: path
        name: key
        required: true
        type: string
      responses:
        "200":
          description: ""
        "400":
          description: param error
          schema:
            type: string
        "404":
          description: key not exists
          schema:
            type: string
      summary: Delete Key and Value
      tags:
      - cache
    get:
      description: Get Value
      parameters:
      - description: key
        in: path
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: param error
          schema:
            type: string
        "404":
          description: key not exists
          schema:
            type: string
      summary: Get Value
      tags:
      - cache
    put:
      description: Add Key and Value
      parameters:
      - description: key
        in: path
        name: key
        required: true
        type: string
      - description: value
        in: body
        name: value
        required: true
        schema:
          type: string
      responses:
        "200":
          description: ""
        "400":
          description: param error
          schema:
            type: string
      summary: Add Key and Value
      tags:
      - cache
  /version:
    get:
      description: Get version
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get version
      tags:
      - cache
swagger: "2.0"
